### ISSUE TITLE
error -> fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by dsky-ac** [actions-x/commit#8]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/85622187/163171645-d8532e56-fcb8-417a-9f77-57ecc98aadd7.png">

**Comment by RikudouSage** [comment]
Can you post the workflow file?

**Comment by divyenduz** [comment]
Related https://github.com/actions/checkout/issues/760

Should we decide to do a hotfix, I think adding `git config --global --add safe.directory /github/workspace` is already enough to fix this (without exposing us to the vulnerability). However, waiting for this to be fixed in `actions/checkout` should be okay.

**Comment by RikudouSage** [comment]
Yep, tested it and it works, it's now released as `v5`.

Tested it on: https://github.com/Unleash/unleash-client-php/runs/6008093082?check_suite_focus=true
